CREATE USER juddiuser IDENTIFIED BY 'juddipass';

CREATE DATABASE juddiv3;

GRANT CREATE,SELECT,INSERT,UPDATE,DELETE,INDEX ON *.* TO 'juddiuser'@'localhost' IDENTIFIED BY 'juddipass' WITH GRANT OPTION;
GRANT CREATE,SELECT,INSERT,UPDATE,DELETE,INDEX ON *.* TO 'juddiuser'@'127.0.0.1' IDENTIFIED BY 'juddipass' WITH GRANT OPTION;
FLUSH PRIVILEGES;
