//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.08 at 10:10:38 PM EST 
//


package gov.hhs.fha.nhinc.pmp.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userInput">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="relaSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="relas" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="drugName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rxclassDrugInfoList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rxclassDrugInfo" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="minConcept">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="rxcui" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="tty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="rxclassMinConceptItem">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="classId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="classType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="rela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="relaSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userInput",
    "rxclassDrugInfoList"
})
@XmlRootElement(name = "rxclassdata")
public class Rxclassdata {

    @XmlElement(required = true)
    protected Rxclassdata.UserInput userInput;
    @XmlElement(required = true)
    protected Rxclassdata.RxclassDrugInfoList rxclassDrugInfoList;

    /**
     * Gets the value of the userInput property.
     * 
     * @return
     *     possible object is
     *     {@link Rxclassdata.UserInput }
     *     
     */
    public Rxclassdata.UserInput getUserInput() {
        return userInput;
    }

    /**
     * Sets the value of the userInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rxclassdata.UserInput }
     *     
     */
    public void setUserInput(Rxclassdata.UserInput value) {
        this.userInput = value;
    }

    /**
     * Gets the value of the rxclassDrugInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link Rxclassdata.RxclassDrugInfoList }
     *     
     */
    public Rxclassdata.RxclassDrugInfoList getRxclassDrugInfoList() {
        return rxclassDrugInfoList;
    }

    /**
     * Sets the value of the rxclassDrugInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rxclassdata.RxclassDrugInfoList }
     *     
     */
    public void setRxclassDrugInfoList(Rxclassdata.RxclassDrugInfoList value) {
        this.rxclassDrugInfoList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rxclassDrugInfo" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="minConcept">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="rxcui" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="tty" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="rxclassMinConceptItem">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="classId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="classType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="rela" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="relaSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rxclassDrugInfo"
    })
    public static class RxclassDrugInfoList {

        @XmlElement(required = true)
        protected List<Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo> rxclassDrugInfo;

        /**
         * Gets the value of the rxclassDrugInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rxclassDrugInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRxclassDrugInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo }
         * 
         * 
         */
        public List<Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo> getRxclassDrugInfo() {
            if (rxclassDrugInfo == null) {
                rxclassDrugInfo = new ArrayList<Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo>();
            }
            return this.rxclassDrugInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="minConcept">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="rxcui" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="tty" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="rxclassMinConceptItem">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="classId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="classType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="rela" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="relaSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "minConcept",
            "rxclassMinConceptItem",
            "rela",
            "relaSource"
        })
        public static class RxclassDrugInfo {

            @XmlElement(required = true)
            protected Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.MinConcept minConcept;
            @XmlElement(required = true)
            protected Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.RxclassMinConceptItem rxclassMinConceptItem;
            @XmlElement(required = true)
            protected String rela;
            @XmlElement(required = true)
            protected String relaSource;

            /**
             * Gets the value of the minConcept property.
             * 
             * @return
             *     possible object is
             *     {@link Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.MinConcept }
             *     
             */
            public Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.MinConcept getMinConcept() {
                return minConcept;
            }

            /**
             * Sets the value of the minConcept property.
             * 
             * @param value
             *     allowed object is
             *     {@link Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.MinConcept }
             *     
             */
            public void setMinConcept(Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.MinConcept value) {
                this.minConcept = value;
            }

            /**
             * Gets the value of the rxclassMinConceptItem property.
             * 
             * @return
             *     possible object is
             *     {@link Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.RxclassMinConceptItem }
             *     
             */
            public Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.RxclassMinConceptItem getRxclassMinConceptItem() {
                return rxclassMinConceptItem;
            }

            /**
             * Sets the value of the rxclassMinConceptItem property.
             * 
             * @param value
             *     allowed object is
             *     {@link Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.RxclassMinConceptItem }
             *     
             */
            public void setRxclassMinConceptItem(Rxclassdata.RxclassDrugInfoList.RxclassDrugInfo.RxclassMinConceptItem value) {
                this.rxclassMinConceptItem = value;
            }

            /**
             * Gets the value of the rela property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRela() {
                return rela;
            }

            /**
             * Sets the value of the rela property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRela(String value) {
                this.rela = value;
            }

            /**
             * Gets the value of the relaSource property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRelaSource() {
                return relaSource;
            }

            /**
             * Sets the value of the relaSource property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRelaSource(String value) {
                this.relaSource = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="rxcui" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="tty" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "rxcui",
                "name",
                "tty"
            })
            public static class MinConcept {

                protected int rxcui;
                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String tty;

                /**
                 * Gets the value of the rxcui property.
                 * 
                 */
                public int getRxcui() {
                    return rxcui;
                }

                /**
                 * Sets the value of the rxcui property.
                 * 
                 */
                public void setRxcui(int value) {
                    this.rxcui = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the tty property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTty() {
                    return tty;
                }

                /**
                 * Sets the value of the tty property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTty(String value) {
                    this.tty = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="classId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="classType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "classId",
                "className",
                "classType"
            })
            public static class RxclassMinConceptItem {

                @XmlElement(required = true)
                protected String classId;
                @XmlElement(required = true)
                protected String className;
                @XmlElement(required = true)
                protected String classType;

                /**
                 * Gets the value of the classId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getClassId() {
                    return classId;
                }

                /**
                 * Sets the value of the classId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setClassId(String value) {
                    this.classId = value;
                }

                /**
                 * Gets the value of the className property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getClassName() {
                    return className;
                }

                /**
                 * Sets the value of the className property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setClassName(String value) {
                    this.className = value;
                }

                /**
                 * Gets the value of the classType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getClassType() {
                    return classType;
                }

                /**
                 * Sets the value of the classType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setClassType(String value) {
                    this.classType = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="relaSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="relas" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="drugName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relaSource",
        "relas",
        "drugName"
    })
    public static class UserInput {

        @XmlElement(required = true)
        protected String relaSource;
        @XmlElement(required = true)
        protected String relas;
        @XmlElement(required = true)
        protected String drugName;

        /**
         * Gets the value of the relaSource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelaSource() {
            return relaSource;
        }

        /**
         * Sets the value of the relaSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelaSource(String value) {
            this.relaSource = value;
        }

        /**
         * Gets the value of the relas property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelas() {
            return relas;
        }

        /**
         * Sets the value of the relas property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelas(String value) {
            this.relas = value;
        }

        /**
         * Gets the value of the drugName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrugName() {
            return drugName;
        }

        /**
         * Sets the value of the drugName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrugName(String value) {
            this.drugName = value;
        }

    }

}
